### ISSUE TITLE
Dropdown menu missing z-index

### ISSUE THREAD

**Issue by madalingorbanescu** [pixelgrade/rosa-lite#16]
There is a problem with the z-index of the menu. The top-level items overlap submenus.
![menu-z-index](https://user-images.githubusercontent.com/46342490/67075107-2a14bf00-f193-11e9-92f0-1d10791b8c7c.jpg)
We should increase z-index for submenus so that it can be shown on top every time.

**Comment by madalingorbanescu** [comment]
I cannot reproduce it. For me is looking like this:
![Screenshot 2019-10-18 at 17 46 54](https://user-images.githubusercontent.com/46342490/67104291-564e3100-f1cf-11e9-8d6f-25075f20bcf3.png)

**Comment by vladolaru** [comment]
Ok. This seems like a very edge-case. Closing it.
