### ISSUE TITLE
Remove filters which are plugin territory

### ISSUE THREAD

**Issue by madalingorbanescu** [pixelgrade/rosa-lite#22]
This is plugin territory:
```// Allow the Text Widgets to handle shortcodes```
```add_filter( 'widget_text', 'shortcode_unautop' );```
```add_filter( 'widget_text', 'do_shortcode' );```

It looks like database has an entry for ```pixtypes_themes_settings``` which it should not have.

The files pixtypes.php and pixcodes.php are calling update_option for non-theme options. Themes should only write to theme options, and theme options should be a single array.

**Comment by vladolaru** [comment]
Yep, removed!
